# Generated by Django 3.0.5 on 2020-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateTimeField(default='1900-01-01', verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
