# Generated by Django 3.0.5 on 2020-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
