# Generated by Django 3.0.7 on 2020-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200425_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Assertiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Assertiveness_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Communication',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Communication_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Diligence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Diligence_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Empathy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Empathy_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Honesty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Honesty_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Kindness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Kindness_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Scrupulousness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Scrupulousness_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Selflessness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Selflessness_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Sincerity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Sincerity_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='body_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='body_type_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='growth_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hair_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hair_color_blonde_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hair_color_brunette_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hair_color_red_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_drinking_alcohol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_drinking_alcohol_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_smoking',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_smoking_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='race_orgin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='race_orgin_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sex_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='weight_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
    ]
