# Generated by Django 3.0.7 on 2020-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200627_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='race_orgin',
            new_name='race_origin',
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
