# Generated by Django 3.0.7 on 2020-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200627_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
