# Generated by Django 3.0.7 on 2020-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200628_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='race_origin',
        ),
    ]
