# Generated by Django 3.0.7 on 2020-06-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200628_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='race_orgin_preference',
        ),
        migrations.RemoveField(
            model_name='matchingform',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='matchingform',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='matchingform',
            name='location',
        ),
        migrations.AddField(
            model_name='matchingform',
            name='body_type_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='growth_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='hair_color_blonde_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='hair_color_brunette_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='hair_color_red_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='sex_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchingform',
            name='weight_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
