# Generated by Django 3.0.7 on 2020-06-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200628_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='matching_form',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MatchingForm'),
        ),
    ]
