# Generated by Django 3.1 on 2020-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200817_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture2',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
