# Generated by Django 3.0.5 on 2020-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200425_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='birth date'),
        ),
    ]
