# Generated by Django 3.0.7 on 2020-06-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200610_2242'),
        ('users', '0006_account_profile_picture'),
    ]

    operations = [
    ]
