# Generated by Django 3.0.7 on 2020-06-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_blonde_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_brunette_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_red_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('growth_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('weight_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('body_type_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(default=None, max_length=30, null=True)),
                ('surname', models.CharField(default=None, max_length=30, null=True)),
                ('birthday', models.DateField(default=None, null=True)),
                ('location', models.CharField(default=None, max_length=30, null=True)),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/')),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('sex', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('growth', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
                ('body_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Assertiveness', models.FloatField(blank=True, default=None, null=True)),
                ('Sincerity', models.FloatField(blank=True, default=None, null=True)),
                ('Empathy', models.FloatField(blank=True, default=None, null=True)),
                ('Communication', models.FloatField(blank=True, default=None, null=True)),
                ('Selflessness', models.FloatField(blank=True, default=None, null=True)),
                ('Honesty', models.FloatField(blank=True, default=None, null=True)),
                ('Scrupulousness', models.FloatField(blank=True, default=None, null=True)),
                ('Diligence', models.FloatField(blank=True, default=None, null=True)),
                ('Kindness', models.FloatField(blank=True, default=None, null=True)),
                ('is_smoking', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_drinking_alcohol', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('sex_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_blonde_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_brunette_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('hair_color_red_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('growth_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('weight_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('body_type_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Assertiveness_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Sincerity_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Empathy_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Communication_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Selflessness_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Honesty_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Scrupulousness_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Diligence_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Kindness_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_smoking_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_drinking_alcohol_preference', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('matching_form', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MatchingForm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
