# Generated by Django 3.0.8 on 2020-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freckles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='freckles_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='glasses_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hair_length',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hair_length_preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
