# Generated by Django 3.1 on 2020-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200725_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='sex_preference',
            new_name='orientation',
        ),
        migrations.AddField(
            model_name='preferences',
            name='age_preference_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='age_preference_min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eye_color',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_place',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passion',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
