# Generated by Django 3.1 on 2020-08-17 10:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.upload_to),
        ),
    ]
