# Generated by Django 3.1 on 2020-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profile_picture2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture2',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
