# Generated by Django 3.1 on 2020-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='messages_settings',
            field=models.CharField(blank=True, default='everybody', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='profile_privacy',
            field=models.CharField(blank=True, default='public', max_length=30, null=True),
        ),
    ]
