# Generated by Django 3.1 on 2020-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201115_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='messages_settings',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='profile_privacy',
        ),
        migrations.AddField(
            model_name='settings',
            name='comments_privacy',
            field=models.CharField(blank=True, default='everybody', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='messages_privacy',
            field=models.CharField(blank=True, default='everybody', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='search_privacy',
            field=models.CharField(blank=True, default='everybody', max_length=30, null=True),
        ),
    ]
