# Generated by Django 3.1 on 2020-11-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201122_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted', to=settings.AUTH_USER_MODEL)),
                ('blacklisting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
