# Generated by Django 3.1 on 2020-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201126_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
