# Generated by Django 3.1 on 2020-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_friendslist_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='accepted',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
