# Generated by Django 3.1 on 2020-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='is_drinking_alcohol_preference',
            field=models.IntegerField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='is_smoking_preference',
            field=models.IntegerField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
