# Generated by Django 3.1 on 2020-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201207_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_drinking_alcohol',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_smoking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
