# Generated by Django 3.1 on 2021-01-11 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201207_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('reported', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('reporting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
