# Generated by Django 3.1 on 2021-01-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendsList',
            new_name='Friend',
        ),
    ]
